name: Lint and Test

# Controls when the action will run.
on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Run Linting
        run: |
          yarn lint
        env:
          CI: true

  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14', '16', '18', '20']
        os: [ubuntu-latest] # [windows-latest, macOS-latest]
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        if: matrix.node_version != 10
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Prepare Environment (Node 10)
        if: matrix.node_version == 10
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

          # yarn --prod

          yarn --ignore-engines
          yarn build
        env:
          CI: true

      - name: Run unit tests
        run: |
          yarn test
        env:
          CI: true
